POST http://localhost:5002/api/example
Content-Type: multipart/form-data; boundary=TrumpWall

--TrumpWall
Content-Disposition: form-data; name="Photo"
Content-Type: image/png

< ./emotions.jpeg

--TrumpWall--